server:
  port: 6061
  address: localhost

mail:
  login: ${EMAIL_LOGIN}
  password: ${EMAIL_PASSWORD}
  sendRealEmails: false
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
  debug: true
  host: smtp.gmail.com
  port: 587

SMSC:
  login: ${SMSC_LOGIN}
  password: ${SMSC_PASSWORD}
  url: https://smsc.ru/sys/send.php

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.nekromant.zoo: INFO
    org.hibernate: ERROR