server:
  port: 6061
  address: localhost

mail:
  login: test@test.ru
  password: password
  sendRealEmails: false
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
  debug: true
  host: smtp.gmail.com
  port: 587

SMSC:
  login: login
  password: password
  url: https://smsc.ru/sys/send.php

spring:
  h2:
    console:
      enabled: false
  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:testdb
    datasource:
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.nekromant.zoo: INFO
    org.hibernate: ERROR